CREATE DATABASE [Service]


CREATE TABLE [Status]
(
	Id INT NOT NULL PRIMARY KEY IDENTITY
	,[Name] NVARCHAR(30) NOT NULL
)

CREATE TABLE Users
(
	Id INT NOT NULL PRIMARY KEY IDENTITY
	,Username NVARCHAR(30) NOT NULL UNIQUE
	,[Password] NVARCHAR(50) NOT NULL
	,[Name] NVARCHAR(50)
	,Birthdate DATETIME2
	,Age INT
	,CHECK (Age >= 14 AND Age <= 110)
	,Email NVARCHAR(50)
)

CREATE TABLE Departments
(
	Id INT NOT NULL PRIMARY KEY IDENTITY
	,[Name] NVARCHAR(50) NOT NULL
)

CREATE TABLE Categories
(
	Id INT NOT NULL PRIMARY KEY IDENTITY
	,[Name] NVARCHAR(50) NOT NULL
	,DepartmentId INT NOT NULL FOREIGN KEY REFERENCES Departments(Id)
)

CREATE TABLE Employees
(
	Id INT NOT NULL PRIMARY KEY IDENTITY
	,FirstName NVARCHAR(25)
	,LastName NVARCHAR(25)
	,Birthdate DATETIME2
	,Age INT
	,CHECK (Age >= 14 AND Age <= 110)
	,DepartmentId INT FOREIGN KEY REFERENCES Departments(Id) 
)

CREATE TABLE Reports
(
	Id INT NOT NULL PRIMARY KEY IDENTITY
	,CategoryId INT FOREIGN KEY REFERENCES Categories(Id) 
	,StatusId INT FOREIGN KEY REFERENCES [Status](Id) 
	,OpenDate DATETIME2 NOT NULL
	,CloseDate DATETIME2
	,[Description] NVARCHAR(200) NOT NULL
	,UserId INT FOREIGN KEY REFERENCES Users(Id) 
	,EmployeeId INT FOREIGN KEY REFERENCES Employees(Id) 

)