CREATE DATABASE [Softuni]

GO

USE [Softuni]

CREATE TABLE [Towns]
(
[Id] BIGINT PRIMARY KEY IDENTITY NOT NULL,
[Name] NVARCHAR(100) NOT NULL
);

CREATE TABLE Addresses
(
[Id] BIGINT PRIMARY KEY IDENTITY NOT NULL,
[AddressText] NVARCHAR(100) NOT NULL,
[TownId] BIGINT FOREIGN KEY REFERENCES Towns(Id) NOT NULL
);

CREATE TABLE Departments
(
[Id] BIGINT PRIMARY KEY IDENTITY NOT NULL,
[Name] NVARCHAR(100) NOT NULL
);

CREATE TABLE Employees
(
[Id] BIGINT PRIMARY KEY IDENTITY NOT NULL,
[FirstName] NVARCHAR(100) NOT NULL,
[MiddleName] NVARCHAR(100),
[LastName] NVARCHAR(100),
[JobTitle] NVARCHAR(100) NOT NULL,
[DepartmentId] BIGINT FOREIGN KEY REFERENCES Departments(Id) NOT NULL,
[HireDate] DATE,
[Salary] DECIMAL(10, 2) NOT NULL,
[AddressId] BIGINT FOREIGN KEY REFERENCES Addresses(Id)
);
